### ISSUE TITLE
Full test of the warc file name patterns

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/netsearch#24]
The values for `job` and `harvest` were not extracted for WARC-file `272839-30-20170313125012768-00000-sb-prod-har-002.statsbiblioteket.dk.warc.gz` as our patterns did not match the _millisecond granularity_, _statsbiblioteket_ and _.warc_-combination.

We should extract _all_ WARC-files from our corpus and run them through the matching rules to see which are not matched and check if more patterns should be added.

**Comment by thomasegense** [comment]
Exported a file with all warc-file names. (4.7M).
Toke will run pattern test against all names.

**Comment by tokee** [comment]
The test has been performed with the code from [webarchive-discovery pull#168](https://github.com/ukwa/webarchive-discovery/pull/168) and _nearly_ passed. 20 files out of 4M+ were not matched. 1 of those was not a WARC file, the remaining 19 shared the same overall naming pattern. This pattern is currently being resolved and a rule for it will be added when done.
